stages:
  GetData:
    cmd: python3 get_data.py
    deps:
    - get_data.py
    outs:
    - data_raw.csv
  ProcessData:
    cmd: python3 process_data.py
    deps:
    - process_data.py
    - data_raw.csv
    outs:
    - data_processed.csv
  TrainData:
    cmd: python3 train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false